#!/bin/bash

echo "🦇 Batman Portfolio - GitHub Deployment Guide"
echo "=============================================="
echo ""

echo "Step 1: Create a GitHub repository"
echo "1. Go to https://github.com/new"
echo "2. Repository name: batman-portfolio (or any name you prefer)"
echo "3. Description: Batman-themed personal portfolio with React and Framer Motion"
echo "4. Set to Public (for free GitHub Pages)"
echo "5. Don't initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""

echo "Step 2: Connect local repository to GitHub"
echo "Replace YOUR_USERNAME with your actual GitHub username:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/batman-portfolio.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "Step 3: Deploy with GitHub Pages"
echo "1. Go to your repository on GitHub"
echo "2. Click 'Settings' tab"
echo "3. Scroll down to 'Pages' in the sidebar"
echo "4. Source: Deploy from a branch"
echo "5. Branch: Select 'main' and '/ (root)'"
echo "6. Click 'Save'"
echo ""

echo "Step 4: Alternative - Deploy with Vercel (Recommended)"
echo "1. Go to https://vercel.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Import your repository"
echo "5. Framework Preset: Vite (auto-detected)"
echo "6. Click 'Deploy'"
echo ""

echo "🎯 Your portfolio will be live at:"
echo "GitHub Pages: https://YOUR_USERNAME.github.io/batman-portfolio"
echo "Vercel: https://batman-portfolio-YOUR_USERNAME.vercel.app"
echo ""

echo "✅ Repository is ready! Your next commands:"
echo "git remote add origin https://github.com/YOUR_USERNAME/batman-portfolio.git"
echo "git push -u origin main"
